- hosts: localhost
  tasks:

    - name: Deploy MySQL StatefulSet to Kubernetes
      command: kubectl apply -f db-statefulset.yaml
      args:
        chdir: sql/k8s

    - name: Export MySQL Service
      command: kubectl apply -f db-service.yaml
      args:
        chdir: sql/k8s
    
    - name: Deploy Backend Application to Kubernetes
      command: kubectl apply -f backend-deployment.yaml
      args:
        chdir: ElectiveManagement/k8s

    - name: Export Backend Service
      command: kubectl apply -f backend-service.yaml
      args:
        chdir: ElectiveManagement/k8s

    - name: Deploy Frontend Application to Kubernetes
      command: kubectl apply -f frontend-deployment.yaml
      args:
        chdir: elecfr-web/k8s

    - name: Export Frontend Service
      command: kubectl apply -f frontend-service.yaml
      args:
        chdir: elecfr-web/k8s