apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: siddharthkothari9403/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: "elective_management"
        - name: MYSQL_USER
          value: "springstudent"
        - name: MYSQL_PASSWORD
          value: "springstudent"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
