apiVersion: apps/v1
kind: Deployment
metadata:
  name: elective-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elective-management
  template:
    metadata:
      labels:
        app: elective-management
    spec:
      containers:
      - name: backend
        image: your-dockerhub-username/elective-management:latest
        ports:
        - containerPort: 8080
