apiVersion: apps/v1
kind: Deployment
metadata:
  name: elecfr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elecfr-web
  template:
    metadata:
      labels:
        app: elecfr-web
    spec:
      containers:
        - name: elecfr-web
          image: siddharthkothari9403/elecfr-web
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: elecfr-web-service
spec:
  selector:
    app: elecfr-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007
  type: NodePort

