apiVersion: apps/v1
kind: Deployment
metadata:
  name: elecfr-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elecfr-web
  template:
    metadata:
      labels:
        app: elecfr-web
    spec:
      containers:
      - name: frontend
        image: siddharthkothari9403/elecfr-web:latest
        ports:
        - containerPort: 80
